image: node:14.16.0
cache:
  paths:
    - dist/

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /gitlab process patch version updated/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /release/'
    - if: '$CI_COMMIT_BRANCH =~ /feat*/'
    - if: '$CI_COMMIT_BRANCH =~ /fix*/'
    - if: '$CI_COMMIT_BRANCH =~ /feature*/'

variables:
  FLAG: ""


# include:
#   - project: 'devops/gitlab-templates'
#     ref: main
    # file: 
      # - '/stages/test/.test_security_template.yml'
      # - '/stages/sonarqube/.pullrequest_analysis_template.yml'

stages:
  - install
  - build
  - test
  - pull_request_analysis
  - gitlab_upload
  - deploy

install:
  stage: install
  cache:
    key: node-module-cache
    paths:
      - node_modules/
  before_script:
    - npm config set registry https://gitlab.com/api/v4/packages/npm/
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
  script:
    - npm ci


build:
  stage: build
  dependencies:
    - install
  cache:
    key: node-module-cache
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
    # - npm run build:bat
    # - npm run build:cit
    # - npm run build:nfr
    # - npm run build:ref
    # - npm run build:prod

  artifacts:
    paths:
      - dist


upload_gitlab:
  stage: gitlab_upload
  allow_failure: false
  rules:
    # If it is an schedule, this job runs
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # If the branch name have "release", this job runs
    - if: $CI_COMMIT_REF_NAME =~ /release/ && $CI_PIPELINE_SOURCE != "merge_request_event"
    # If the branch is main, this job runs
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
  script:
     - >
      if [ -f "$CI_PROJECT_DIR/.npmrc" ]; then
        echo "//gitlab.com/api/v4/projects/64447953/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
        npm publish --registry https://gitlab.com/api/v4/projects/64447953/packages/npm/
      else
        echo "registry=https://gitlab.com/api/v4/packages/npm/" >.npmrc
        echo "//gitlab.com/api/v4/packages/npm/:_authToken'=${CI_JOB_TOKEN}" >>.npmrc
        echo "//gitlab.com/api/v4/projects/64447953/packages/npm/:_authToken=${CI_JOB_TOKEN}" >>.npmrc
        npm publish --registry https://gitlab.com/api/v4/projects/64447953/packages/npm/
      fi



deploy_dev:
  dependencies:
    - build
  variables:
    BUCKET_PATH: NEXTCALL
    FILES_DEPLOY_PATH: dist/NEXTCALL/**
  image: google/cloud-sdk:slim
  stage: deploy
  when: manual
  script: |-
    echo "$SERVICE_ACCOUNT_KEY" > key.json
    gcloud auth activate-service-account --key-file=key.json
    gcloud config set project gke-greentech
    gsutil -D -h Cache-Control:"Cache-Control:private, max-age=0, no-transform" -m cp -r $FILES_DEPLOY_PATH gs://$BUCKET_PATH
    gcloud compute url-maps invalidate-cdn-cache $BUCKET_PATH --path "/*"
